### ISSUE TITLE
Estimate gas & storage limits by making a dry run

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/ConseilJS#146]
Wrap [head/helpers/scripts/run_operation](https://tezos.gitlab.io/mainnet/api/rpc.html#post-block-id-helpers-scripts-run-operation) RPC call. Add explicit return types in `src/types/tezos/TezosChainTypes.ts`.

**Comment by anonymoussprocket** [comment]
Addresses the same concerns as to #9, #72.
