### ISSUE TITLE
Get account balance from Tezos RPC interface

### ISSUE THREAD

**Issue by cryptofuture** [Cryptonomic/ConseilJS#201]
Wrap the RPC call to return account balance as of HEAD.

**Comment by anonymoussprocket** [comment]
This is already possible with this call: `TezosNodeReader.getAccountForBlock(tezosNodeUrl, 'head', accountHash)` which would return an object of this structure:

```
{
    "manager": "xxx",
    "balance": "000",
    "spendable": true,
    "delegate": { "setable": false },
    "counter": "000"
}
```

However, `TezosNodeReader.getSpendableBalanceForAccount()` was added.
