### ISSUE TITLE
NPM package update required

### ISSUE THREAD

**Issue by jvtezsure** [Cryptonomic/ConseilJS#203]
conseiljs has latest npm package version : 0.2.6
But this package doesn't have 'TezosParameterFormat' class and hence 'conseiljs.TezosParameterFormat.Michelson' is not accessible.

I built the latest code and used dist in my project and it worked fine. Can someone push the latest code to the npm package?

**Comment by anonymoussprocket** [comment]
There is a beta nom package version 0.2.9, please try that.

**Comment by jvtezsure** [comment]
Thank you.
