### ISSUE TITLE
node-hid dependency for latest node versions

### ISSUE THREAD

**Issue by jvtezsure** [Cryptonomic/ConseilJS#212]
i'm using 
node : 12.3.1
npm : 6.9.0 
I'm not able to use conseilJS package as it fails rebuilding 'node-hid' for me. It tries to find a prebuild binary for my node&OS but when it doesn't find, it tries to rebuild.

Can you update minimum version of node-hid in package-lock.json for '@ledgerhq/hw-transport-node-hid'? 
Updating it from 0.7.2 to 0.7.9 eems to be working fine for me.

**Comment by anonymoussprocket** [comment]
ConseilJS 0.4.0 is build with 12.13.1
