### ISSUE TITLE
Signing Tezos transactions client side

### ISSUE THREAD

**Issue by kss-espeo** [Cryptonomic/ConseilJS#241]
Hello. I would like to use ConseilJS to integrate my app with Tezos, but it is necessary that I'm able to sign transactions on the client side and then to just submit a signed transaction to blockchain.

What I have in mind is something similar to `eztz`'s  [sign method](https://github.com/TezTech/eztz/wiki/Documentation#eztzcryptosignbytes-sk-wm) . 

Is there such feature in ConseilJS? My guess is there's not, since there is no relevant type in `TezosP2PMessageTypes` . In such case, are you planning to implement that? 

If you are not, I would be interested in creating a fork and writing it myself as it sounds like a relatively easy task, not requiring much of a project context. Do you think this could be facilitated and then, merged into Conseil and reasonably maintained? If  such fork was not to be maintaned by Conseil team, it is probably not worth it since I can just interact with Tezos Node's REST API.

Thanks,
Kris

**Comment by anonymoussprocket** [comment]
ConseilJS enables fully trustless operations against the Tezos platform, down to contract encoding.

For your specific question, take a look at [TezosNodeWriter.signOperationGroup()](https://github.com/Cryptonomic/ConseilJS/blob/release/040/src/chain/tezos/TezosNodeWriter.ts#L55) and how it uses [CryptoUtils.signDetached()](https://github.com/Cryptonomic/ConseilJS/blob/release/040/src/utils/CryptoUtils.ts#L100). If you have follow-up questions, please reach out on the [Riot dev chat](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org).
