### ISSUE TITLE
Can a fee estimate method be implemented without private key?

### ISSUE THREAD

**Issue by kss-espeo** [Cryptonomic/ConseilJS#250]
I have a question related to fee estimate method (https://github.com/Cryptonomic/ConseilJS/blob/master/src/chain/tezos/TezosNodeWriter.ts#L587)

It requires `keyStore` , specifically a `privateKey` that is used to actually sign a test transaction prior sending it to a Tezos node.
This is unusual - fee estimate methods in other blockchains do not require a private key. After all, this is just a fee estimate and we are not recording anything on blockchain.

Do you think it is necessary or could be potentially implemented without needing a private key? Does a `chains/${chainid}/blocks/head/helpers/scripts/run_operation` Tezos node controller actually require a signature to provide a fee estimate? I know it is in the call parameters but I just don't understand what it would need signature for.

Of course best case scenario would be if you provided such implementation but if we can confirm that this can be done, I'm happy to do that myself and submit a PR to `ConseilJS` .

Thanks,
Kris

**Comment by kss-espeo** [comment]
Turns out it's possible! As long as you send any valid signature as input to `chains/${chainid}/blocks/head/helpers/scripts/run_operation` , it's going to work. The way to go is probably to just always send some hardcoded signature.

**Comment by anonymoussprocket** [comment]
Removing the signature field or making it blank causes the RPC call to fail. Instead the signature was hard-wired to a conforming value that is not related to the actual payload.
