### ISSUE TITLE
Michelson contract fails to convert

### ISSUE THREAD

**Issue by piotrkosecki** [Cryptonomic/ConseilJS#255]
Issue originally created in Conseil repo by mistake:
https://github.com/Cryptonomic/Conseil/issues/684

https://smart-contracts-micheline-michelson-translator-for-tezos.scalac.io which uses our JS parser fails for parsing following contract:
https://tezos-prod.cryptonomic-infra.tech/chains/main/blocks/BLGkUWx1PWPMKnrc1PjGECneRKK7AA8SKg1CN1YfTX1aLQEWVq4/context/contracts/KT19ZSNkZ1wNdmHRQ9tYVgmMChmpqCyCus2M

This contract comes from Conseil but it looks the same as an original contract from Tezos. Therefore it should be parsable so there's probably a bug in our JS parser.

**Comment by anonymoussprocket** [comment]
ConseilJS does not have the parser for converting Micheline (json-encoding) into Michelson. The contract conversion pipeline is Michelson -> Micheline -> Hex.
