### ISSUE TITLE
public tezos node 4o4

### ISSUE THREAD

**Issue by lijianl** [Cryptonomic/ConseilJS#263]
1. URL from nautilus.cloud is 404
such as https://tezos-dev.cryptonomic-infra.tech and https://tezos-prod.cryptonomic-infra.tech/,  these two URL are 404
2. there is not Bablylonnet on https://conseil-dev.cryptonomic-infra.tech/; 
3. where could I find a tezos public node? all links are empty
4. tezos account which gets from https://faucet.tzalpha.net/ are not available on https://testnet.dunscan.io/

where such important  Infos from the official page are not work?????

**Comment by anonymoussprocket** [comment]
1. The servers are functional, but you have be calling specific RPCs.
2. We decommissioned babylonnet support, our development infrastructure now runs carthagenet.
3. ...
4. You can activate faucet.tzalpha.net accounts following the instructions in my [workflows gist] (https://gist.github.com/anonymoussprocket/148d82fc9bf6c413be04155a90d57be6) You can then confirm the transactions on [mininax](https://mininax.io/carthagenet).
