### ISSUE TITLE
no api to validate a address

### ISSUE THREAD

**Issue by lijianl** [Cryptonomic/ConseilJS#264]
how to validate an address?

there is no API to solve this problem,  SOS??

**Comment by anonymoussprocket** [comment]
What's the use-case?

**Comment by lijianl** [comment]
use for a wallet server, to transfer value to a new address

**Comment by anonymoussprocket** [comment]
You can use getAccount to see if it exists, but 0-balance accounts aren't always "live".

**Comment by lijianl** [comment]
async function createAccount() {
    const mnemonic = conseiljs.TezosWalletUtil.generateMnemonic();
    console.log(`mnemonic: ${mnemonic}`);
    const keystore = await conseiljs.TezosWalletUtil.unlockIdentityWithMnemonic(mnemonic, '');
    console.log(`account id: ${keystore.publicKeyHash}`);
    console.log(`public key: ${keystore.publicKey}`);
    console.log(`secret key: ${keystore.privateKey}`);
}

a new account created with above function could be activated? where is activationCode
