### ISSUE TITLE
unable to deploy a contract with byte type in initial storage.

### ISSUE THREAD

**Issue by baahkusi** [Cryptonomic/ConseilJS#265]
Here is my code with a contract having byte type as initial storage.
https://github.com/baahkusi/tezos-secrets-store/blob/master/secrets/src/contract.js
In this JS file I have the same contract in michelson an micheline format.

When I use the micheline format I get the error as I have reported here https://tezos.stackexchange.com/questions/2367/i-got-this-error-from-conseil-js-tezosnodewriter-sendcontractoriginationoperatio.

when I use the michelson format I get the following errors 

`"[proto.006-PsCARTHA.michelson_v1.ill_typed_data,proto.006-PsCARTHA.invalidSyntacticConstantError,proto.006-PsCARTHA.invalidSyntacticConstantError,proto.006-PsCARTHA.michelson_v1.invalid_expression_kind]"`

The problem seems to come from conseiljs since the same contract has been deployed with tezos-client and works just fine.

Here is also main code for deployment https://github.com/baahkusi/tezos-secrets-store/blob/072c3d07a23d05872663647eb11d10e0b6c68535/secrets/src/main.js#L90

**Comment by anonymoussprocket** [comment]
The issue is encoding of `bytes`-type.
