### ISSUE TITLE
gather value

### ISSUE THREAD

**Issue by lijianl** [Cryptonomic/ConseilJS#266]
async function createAccount() {
const mnemonic = conseiljs.TezosWalletUtil.generateMnemonic();
console.log(mnemonic: ${mnemonic});
const keystore = await conseiljs.TezosWalletUtil.unlockIdentityWithMnemonic(mnemonic, '');
console.log(account id: ${keystore.publicKeyHash});
console.log(public key: ${keystore.publicKey});
console.log(secret key: ${keystore.privateKey});
}

a new account created for a new user with above function to receive the value.
it is possible to gather the value to a unique account?  and need to activate this account? 
 how to get a activateCode

**Comment by anonymoussprocket** [comment]
These types of accounts do not need to be activated. Activation is only for fundraiser and faucet accounts. Please address further questions to the [Cryptonomic Riot developer room](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org)

**Comment by lijianl** [comment]
Your Riot is misconfigured
Invalid homeserver discovery response....

**Comment by lijianl** [comment]
> These types of accounts do not need to be activated. Activation is only for fundraiser and faucet accounts. Please address further questions to the [Cryptonomic Riot developer room](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org)

the link is ERROR,Invalid homeserver discovery response
