### ISSUE TITLE
Fix directory traversal in wallet name

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/ConseilJS#28]
In `saveWallet()` in `TezosWallet`, please implement the following:

![image](https://user-images.githubusercontent.com/931163/42258426-b75d5f80-7f29-11e8-848b-00345933f192.png)

**Comment by developer0623** [comment]
We use the whole path on  **Tezos-Wallet**.
There is no way to separate the filename here.
`export async function saveUpdatedWallet(identities, walletLocation, walletFileName, password) {
  const completeWalletPath = path.join(walletLocation, walletFileName);

  identities = identities
    .map(({ publicKey, privateKey, publicKeyHash }) => {
      return { publicKey, privateKey, publicKeyHash };
    });

  return await saveWallet( completeWalletPath, { identities }, password );
}`
