### ISSUE TITLE
unauthorized error

### ISSUE THREAD

**Issue by priya-optisol** [Cryptonomic/ConseilJS#282]
Hi Team,
I am using conseiljs. from the document I have generated the account and then I initialized the account, but it throws http error message as unauthorized. I have created key in nautilus. Kindly help me to clear the unauthorized error

Reference - https://cryptonomic.github.io/ConseilJS/#/?id=initialize-the-account 

same reference code

const conseiljs = require('conseiljs');
const tezosNode = 'https://conseil-dev.cryptonomic-infra.tech:443/';
async function activateAccount() {
     const keystore = {
        publicKey: 'edpkvQtuhdZQmjdjVfaY9Kf4hHfrRJYugaJErkCGvV3ER1S7XWsrrj',
        privateKey: 'edskRgu8wHxjwayvnmpLDDijzD3VZDoAH7ZLqJWuG4zg7LbxmSWZWhtkSyM5Uby41rGfsBGk4iPKWHSDniFyCRv3j7YFCknyHH',
        publicKeyHash: 'tz1QSHaKpTFhgHLbqinyYRjxD5sLcbfbzhxy',
        seed: '',
        storeType: conseiljs.StoreType.Fundraiser
    };
    try{
	    const result = await conseiljs.TezosNodeWriter.sendIdentityActivationOperation(tezosNode, keystore, '0a09075426ab2658814c1faf101f53e5209a62f5');
	    console.log(result);
	    console.log(`Injected operation group id `,result.operationGroupID)

    }catch(err){
    	console.log(err);
    }
}

activateAccount();

![Screenshot from 2020 05 19 16 13 03 png  PNG Image  1600 × 900 pixels    Scaled  89  ](https://user-images.githubusercontent.com/13196091/82317578-1e6ccd80-99ec-11ea-8be5-2068a7417185.png)

**Comment by anonymoussprocket** [comment]
Hi, you're using the wrong server, `conseil-dev` is the [Conseil indexer](https://github.com/Cryptonomic/Conseil). You're looking for `tezos-dev`, same domain, which is a tezos node.
