### ISSUE TITLE
ConseilJs library Transfer issue

### ISSUE THREAD

**Issue by desingraja** [Cryptonomic/ConseilJS#286]
I tried this one for transfer operation in Tezos Network   
 const keystore = {
        publicKey: '',
        privateKey: '',
        publicKeyHash: '',
        storeType: conseil.StoreType.Fundraiser
    };

    const result = await conseil.TezosNodeWriter.sendTransactionOperation(tezosNode, keystore, 'to_address', 100000, 100, '');
    console.log(`Injected operation group id ${result.operationGroupID}`);

But I got the error as  - Error: (permanent: proto.004-Pt24m4xi.operation.invalid_signature).
Kindly give the solution for this operation, if anyone knows

**Comment by anonymoussprocket** [comment]
That's an odd error specifically because it reads `proto.004-Pt24m4xi`. Current protocol is 005 and is available as "Carthagenet" test net. You can signup at [nautilus.cloud](https://nautilus.cloud/) and get access to Cryptonomic infra for testing.
