### ISSUE TITLE
Not able to recover the error message originated from failwith.

### ISSUE THREAD

**Issue by m0107** [Cryptonomic/ConseilJS#299]
Hello everyone,

I am trying to invoke my contract with conseiljs.TezosNodeWriter.sendContractInvocationOperation().

Everything works fine with a positive scenario but when I purposely fail the script with some error message like "not enough balance".

All I get in try-catch is  :
```
Error: failed: (temporary: proto.006-PsCARTHA.michelson_v1.runtime_error), (temporary: proto.006-PsCARTHA.michelson_v1.script_rejected)
```
It just says that your script failed because it hit failwith somewhere but I want the message.
Is there any way to do it ?
I was not able to find anything in the documentation.
Thanks in advance.

**Comment by anonymoussprocket** [comment]
Sounds like the contract rejected your transaction for one reason or another. I would expect that it's a `FAIL` or `FAILWITH` in the code of the contract itself.

**Comment by m0107** [comment]
Hi @anonymoussprocket 
Yes, I know it is failing, that's what the logic is supposed to do.
The **problem** is I am not able to recover the error code returned by the ```FAIL``` or ```FAILWITH```  statement.
for eg: its returns "31".
I am not able to find any way in conseilJS to do so.
It will be great If you know if you can point me to the answer.
Thanks.
