### ISSUE TITLE
Issue with functions

### ISSUE THREAD

**Issue by Rakshak1344** [Cryptonomic/ConseilJS#307]
I'm working on recreating the whole ConseilJS package in the dart called [Tezster_dart](https://pub.dev/packages/tezster_dart).
I have already had the 1st version deployed. I got stuck at this point.
![image](https://user-images.githubusercontent.com/35299775/87125672-84692900-c2a8-11ea-9c86-bff37e0cb65d.png)

I could not understand the difference between those lines.
1. ` r.greater(0)` and `r > 0`
2.  `r.and(127)` and `r & 127`
3.  `r.shiftRight(7)` and `r >> 7`

I could not find the alternative, can you guide me through this problem.
https://github.com/Cryptonomic/ConseilJS/blob/f7192a8a32cbf90f6b583a850d85b2cf6b12102a/src/utils/CryptoUtils.ts#L96

**Comment by anonymoussprocket** [comment]
Hi @Rakshak1344, this function handles large numbers in javascript with bignumber.js and smaller numbers natively in javascript.
