### ISSUE TITLE
Tezos: Support for Multiple Contract calls in one Operation

### ISSUE THREAD

**Issue by atomantic** [Cryptonomic/ConseilJS#377]
Is there a way using conseil to submit multiple contracts in a single operation?

It appears that `TezosNodeWriter.sendContractInvocationOperation` only accepts a single entrypoint and parameter. I have an operation that requires 3 contracts to be invoked.

**Comment by anonymoussprocket** [comment]
it's possible to package operations into an operation group: [TezosNodeWriter.sendOperation](https://github.com/Cryptonomic/ConseilJS/blob/master/src/chain/tezos/TezosNodeWriter.ts#L194)
