### ISSUE TITLE
get nothing from api 

### ISSUE THREAD

**Issue by lijianl** [Cryptonomic/ConseilJS#390]
`
// opWvamznrS5VLUSqNxungkMJfYc24eF5iuyBiBCJ8KtwgHbYAyx
let tx = conseiljs.TezosConseilClient.getOperations(conseilServer, conseilServer.network, transactionQuery);
`
why get nothing from api of this hash

https://tzkt.io/opWvamznrS5VLUSqNxungkMJfYc24eF5iuyBiBCJ8KtwgHbYAyx

**Comment by anonymoussprocket** [comment]
i'm able to load that block both by [level](https://arronax.io/tezos/mainnet/blocks/query/eyJmaWVsZHMiOlsidGltZXN0YW1wIiwibWV0YV92b3RpbmdfcGVyaW9kIiwibWV0YV9jeWNsZSIsImxldmVsIiwiYmFrZXIiLCJoYXNoIiwicHJpb3JpdHkiXSwicHJlZGljYXRlcyI6W3siZmllbGQiOiJsZXZlbCIsIm9wZXJhdGlvbiI6ImVxIiwic2V0IjpbIjE3NDkzMTkiXSwiaW52ZXJzZSI6ZmFsc2V9XSwib3JkZXJCeSI6W3siZmllbGQiOiJsZXZlbCIsImRpcmVjdGlvbiI6ImRlc2MifV0sImFnZ3JlZ2F0aW9uIjpbXSwibGltaXQiOjUwMDB9) and by [hash](https://arronax.io/tezos/mainnet/blocks/query/eyJmaWVsZHMiOlsidGltZXN0YW1wIiwibWV0YV92b3RpbmdfcGVyaW9kIiwibWV0YV9jeWNsZSIsImxldmVsIiwiYmFrZXIiLCJoYXNoIiwicHJpb3JpdHkiXSwicHJlZGljYXRlcyI6W3siZmllbGQiOiJoYXNoIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsiQk1XRjZmdEFDNXhIOEw5aDM4blNIblY0NDdEdlk0aldLd3V5UmdxdE51OHdoUEhqVjgxIl0sImludmVyc2UiOmZhbHNlfV0sIm9yZGVyQnkiOlt7ImZpZWxkIjoibGV2ZWwiLCJkaXJlY3Rpb24iOiJkZXNjIn1dLCJhZ2dyZWdhdGlvbiI6W10sImxpbWl0Ijo1MDAwfQ).
