### ISSUE TITLE
Change StoreType type from enum to string

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/ConseilJS#41]
https://github.com/Cryptonomic/ConseilJS/blob/master/src/types/KeyStore.ts#L16 should export strings

```
export const MNEMONIC = 'Mnemonic';
export const FUNDRAISER = 'Fundraiser';
```

**Comment by umurb** [comment]
I opened this ticket and #40 as per @yanivkalfa ‘s request. He can help you with your request

**Comment by vishakh** [comment]
No longer in scope.
