### ISSUE TITLE
NPM Package not available

### ISSUE THREAD

**Issue by Sm00g15** [Cryptonomic/ConseilJS#42]
Looking to use your client side library but it looks like the NPM package isn't available. Any idea when this will be available again?

**Comment by Sm00g15** [comment]
ah, had not tried. When I head to the link on the README  (https://github.com/Cryptonomic/ConseilJS/blob/master) it sent me to a 404 page on Github so just assumed! Thank you

**Comment by Sm00g15** [comment]
how can we apply for an API key?

**Comment by vishakh** [comment]
@Sm00g15 You just have to ask. :smile: Please send an email to support@cryptonomic.tech.
