### ISSUE TITLE
Refactor branches and packages to reflect multiple environments

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/ConseilJS#54]
All code in the `master` branch should be compatible with the Tezos `mainnet` and should be published as the ConseilJS NPM package.
All code in the `staging` branch should be compatible with the Tezos `zeronet` and should be published as the ConseilJS-staging NPM package.
All code in the `develop` branch should be compatible with the Tezos `alphanet` and should be published as the ConseilJS-dev NPM package.*

The above information should be included in the root README file.

*As Cryptonomic is not yet running `alphanet` nodes, we must use `zeronet` for now.

**Comment by anonymoussprocket** [comment]
There are no functional differences between the three environments now that `managerPubkey` issue has been resolved
