### ISSUE TITLE
Reveal operations should not incur fees

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/ConseilJS#64]
Currently, reveals incur fees, and since reveals are now bundled with transactions, delegations, and originations, there can be unexpected doubling of fees. We want reveals to not insure any fees, even when bundled with other operations.

**Comment by developer0623** [comment]
It seems @ba205 fixed it, already

**Comment by anonymoussprocket** [comment]
This is no longer the case with Protocol 003.
